#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("jy_App.Resource", IsApplication=true)]

namespace jy_App
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int back = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int btn_state_green = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int btn_state_login = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int btn_state_red = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int btn_state_setting = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int check = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int down = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int ic_launcher = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int img_in = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int img_new = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int img_search = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int img_send = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int kuaidiyuan = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int one = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int print_again = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int shape_blue_clickable = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int shape_blue_unclickable = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int shape_green_clickable = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int shape_green_unclickable = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int shape_red_clickable = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int shape_red_unclickable = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int shape_setting_clickable = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int shape_setting_unclickable = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int up = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int z = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int zt = 2130837529;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050009
			public const int btn_exit = 2131034121;
			
			// aapt resource value: 0x7f050006
			public const int btn_getNewVersion = 2131034118;
			
			// aapt resource value: 0x7f050003
			public const int btn_login = 2131034115;
			
			// aapt resource value: 0x7f050007
			public const int btn_server_select = 2131034119;
			
			// aapt resource value: 0x7f050004
			public const int btn_setting = 2131034116;
			
			// aapt resource value: 0x7f050005
			public const int btn_wifi = 2131034117;
			
			// aapt resource value: 0x7f050002
			public const int edi_password = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int edi_username = 2131034113;
			
			// aapt resource value: 0x7f050008
			public const int test = 2131034120;
			
			// aapt resource value: 0x7f050000
			public const int tv_version = 2131034112;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Login = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Main = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Setting = 2130903042;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int app_name = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
